### ISSUE TITLE
Stopped working about a week ago

### ISSUE THREAD

**Issue by regnatarajan** [stvedt/Flickr-Automated-Unfollow#15]
This script reliably worked for a long time, but recently stopped working on several different computers about a week ago.  I realize this is very little information to go on, but I have very little to provide.  The pages still advance correctly but they do so almost immediately, without unfollowing anyone.

**Comment by koperman** [comment]
Yes I have the same problem and that appended 3 weeks ago. 
I posted it to Stvedt some minutes ago.
I am sure he can solve it.

**Comment by stvedt** [comment]
I will take a look when I get a chance.

**Comment by koperman** [comment]
Once again many thanks Stephen & have a nice weekend !

**Comment by koperman** [comment]
Happy New Year 2018 Stephen !

I hope it’s not so complicated to solve the issue of your helpful script.

**Comment by Starlashine** [comment]
Hey Stephen! I pray for this script, and hope you can fix it very soon. 
Thank you for your hard work!

**Comment by stvedt** [comment]
Update: I started to look into this and seems the latest version of firefox doesn't support some of my syntax. I will continue to look for a solution but may take some time.

**Comment by regnatarajan** [comment]
I don't think this is a Firefox issue.  The script worked fine in Firefox/Greasemonkey **_and_** in Chrome/Tampermonkey and stopped working across all browsers at the same time.

**Comment by koperman** [comment]
Hello Stephen, did you find any improvement for your script ?
Thanks in advance for your answer !
BR.

**Comment by stvedt** [comment]
I did look into this with no luck. When I have some more free time I will try again. Thanks for the patience on this.

**Comment by stvedt** [comment]
Update everyone. I believe the issue is some new security preferences with UserScripts in Mozilla.

Please continue to use the script in Google Chrome with the [Tampermonkey Extension](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=en)

Apologies for the delay looking into this.

**Comment by stvedt** [comment]
@koperman @regnatarajan Can you guys give the above a try?
