### ISSUE TITLE
Script doesn't work  Firefox 37.0.2 

### ISSUE THREAD

**Issue by Pistenwolf** [stvedt/Flickr-Automated-Unfollow#2]
Hello stvedt,

try to get your Script to work but it doesnt. Nothing happen (no red highligted contacts or the renamed text to "unfollow") if i activate it.
Your " unfollow one click" - Script  and the "Non - Reciprocal Contacts Finder " - Script works fine on the same machine. I use them both individually at the same time (of course deactivated as i try your new script). Maybe you could help me why your  script didnt work, i would be very happy if i could use it.

Best Regards,

Pistenwolf

**Comment by stvedt** [comment]
Are there any errors appearing in the Console? 

I'm going to push a quick update as I've made some small changes to the one I've been using.
